services:
- type: web
  name: flask-app
  env: python
  buildCommand: ""
  startCommand: gunicorn -w 4 -b 0.0.0.0:8000 flask_app.app:app
  plan: free
  envVars:
  - key: FLASK_ENV
    value: production